services:
  redoproxy:
    image: ghcr.io/mikhail-angelov/redoproxy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/data/autocert
    env_file:
      - .env
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
